name: air
on:
  workflow_dispatch:
    inputs:
      AIR_VER:
        description: 'Air version'
        type: string
        required: true
jobs:
  builds:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download/Extract air
        run: |
          wget https://github.com/posit-dev/air/archive/refs/tags/${{inputs.AIR_VER}}.tar.gz
          tar xaf ${{inputs.AIR_VER}}.tar.gz
      #Checkout git sources
      - name: Checkout Current
        uses: actions/checkout@v7
        with:
          path: file_repo
      - name: Pycargobuild
        uses: ./file_repo/.github/actions/pycargoebuild
        with:
          cargo-root-path: "air-${{inputs.AIR_VER}}/crates/air"
          crate-name: "air"
          crate-version: ${{inputs.AIR_VER}}

