name: Rstudio-9999
on:
  workflow_dispatch:
    inputs:
      RSTUDIO_REF:
        description: 'Git hash/branch/date to clone from RStudio'
        type: string
        required: true
        default: 'main'
jobs:
  builds:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
#Checkout git sources
      - name: Checkout Current
        uses: actions/checkout@v3
        with:
          path: file_repo
      - name: Checkout Current
        uses: actions/checkout@v3
        with: 
          repository: rstudio/rstudio
          ref: ${{ inputs.RSTUDIO_REF }}
          path: rstudio
          fetch-depth: 450
      - name: Get/Set Quarto branch
        working-directory: rstudio
        run: |
          BRANCH=$(grep '^ \+git clone --branch' dependencies/common/install-panmirror |sed "s/.*--branch \(\S*\).*/\1/")
          echo "quarto_branch=${BRANCH:-main}" >> $GITHUB_ENV
      - name: Checkout Current
        uses: actions/checkout@v3
        with:
          repository: quarto-dev/quarto
          ref: ${{env.quarto_branch}}
          path: rstudio/src/gwt/lib/quarto
#Set Variables
      - name: Get/Set Files repo Version
        working-directory: file_repo
        run: |
          echo "file_repo_ver=`git branch --show-current`" >> $GITHUB_ENV
          echo "file_repo_sha=`git rev-parse HEAD`"        >> $GITHUB_ENV

      - name: Get/Set RStudio Version
        working-directory: rstudio
        run: |
          my_pv="$(<version/CALENDAR_VERSION).0."
          flower="$(<version/RELEASE)"
          flower=${flower,,}
          base_commit=$(< version/base_commit/${flower/ /-}.BASE_COMMIT)
          my_pv+="$(git rev-list ${base_commit}..HEAD --count)"
          echo "rstudio_ver=${my_pv}"             >> $GITHUB_ENV
          echo "rstudio_sha=`git rev-parse HEAD`" >> $GITHUB_ENV

          echo electron_ver=$(jq ".devDependencies.electron" src/node/desktop/package.json) >> $GITHUB_ENV
      - name: Get/Set Quarto Version
        working-directory: rstudio/src/gwt/lib/quarto
        run: |
          echo "quarto_ver=`git branch --show-current`" >> $GITHUB_ENV
          echo "quarto_sha=`git rev-parse HEAD`"        >> $GITHUB_ENV

      - name: Print Version info
        run: |
          echo "Files Repo Version:${{env.file_repo_ver}}"
          echo "Files Repo Commit :${{env.file_repo_sha}}"
          echo "RStudio Version:${{env.rstudio_ver}}"
          echo "Rstudio Commit :${{env.rstudio_sha}}"
          echo "Quarto Version:${{env.quarto_ver}}"
          echo "Quarto Branch :${{env.quarto_ver}}"
          echo "Quarto Commit :${{env.quarto_sha}}"
#Setup Node-18
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
# Build Quarto
# This was inspired by  https://src.fedoraproject.org/rpms/rstudio
      - name: Remove non-Panmirror folders
        working-directory: rstudio/src/gwt/lib/quarto
        run: |
          rm -r packages/{eslint-config-custom,eslint-config-custom-server,ojs}
          rm -r apps/{writer,writer-server,vscode,vscode-editor,lsp}
      - name: Patch Quarto
        working-directory: rstudio/src/gwt/lib/quarto
        run: |
          esbuild_version="0.15.6"
          cp ${GITHUB_WORKSPACE}/file_repo/sci-mathematics/rstudio/panmirror-base-9999.patch panmirror-base.patch
          patch -p1 -i panmirror-base.patch
          sed -i "/eslint/d"  apps/panmirror/package.json packages/*/package.json
          sed -i "s/\"esbuild\":.*/\"esbuild\": \"${esbuild_version}\",/g" packages/build/package.json
          git diff package.json packages/*/package.json apps/panmirror/package.json > panmirror.patch
      - name: Build Quarto
        working-directory: rstudio/src/gwt/lib/quarto
        run: yarn install
      - name: Clean up Quarto-Panmirror node_modules
        working-directory: rstudio/src/gwt/lib/quarto
        run: |
          rm node_modules/vite/node_modules/esbuild-linux-64/bin/esbuild node_modules/esbuild-linux-64/bin/esbuild
          echo "Deleteing binaries in panmirror"
          find node_modules -name "*.node" -delete -print
          find node_modules -name "*.o" -delete -print
          tar caf /tmp/rstudio-${{env.rstudio_ver}}-panmirror-node_modules.tar.xz node_modules/ panmirror.patch panmirror-base.patch
# Build RStudio Electron
      - name: Build Electron node_modules
        working-directory: rstudio/src/node/desktop
        run: npm install
      - name: Clean up node_modules
        working-directory: rstudio/src/node/desktop
        run: |
          rm -r node_modules/electron/dist/*
          echo "Deleteing binaries in electron"
          find node_modules/ -name "*.node" -delete -print
          find node_modules/ -name "*.o" -delete -print
      - name: Make Rstudio-Electron node_modules tarball
        working-directory: rstudio/src/node/desktop
        run: tar caf /tmp/rstudio-${{env.rstudio_ver}}-electron-node_modules.tar.xz node_modules/
# Upload Files
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Rstudio ${{env.rstudio_ver}}
          body: |
            Files Repo: ${{env.file_repo_ver}} - ${{env.file_repo_sha}}
            RStudio: ${{env.rstudio_ver}} - [${{env.rstudio_sha}}](https://github.com/rstudio/rstudio/tree/${{env.rstudio_sha}})
            Quarto:  ${{env.quarto_ver}} - ${{env.quarto_branch}} - [${{env.quarto_sha}}](https://github.com/quarto-dev/quarto/tree/${{env.quarto_sha}})
            Electron Version: ${{env.electron_ver}}
          tag_name:  rstudio-${{env.rstudio_ver}}
          files: |
            /tmp/rstudio-${{env.rstudio_ver}}-panmirror-node_modules.tar.xz
            /tmp/rstudio-${{env.rstudio_ver}}-electron-node_modules.tar.xz

