name: typst-gather
on:
  workflow_dispatch:
     inputs:
      TYPST_GATHER_VER:
        description: 'Typst-gather version'
        type: string
        required: true
jobs:
  builds:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download/Extract typst-gather
        run: |
          wget https://github.com/quarto-dev/typst-gather/archive/refs/tags/v${{inputs.TYPST_GATHER_VER}}.tar.gz
          tar xaf v${{inputs.TYPST_GATHER_VER}}.tar.gz
      - name: Checkout Current
        uses: actions/checkout@v7
        with:
          path: file_repo
      - name: Pycargobuild
        uses: ./file_repo/.github/actions/pycargoebuild
        with:
          cargo-root-path: "typst-gather-${{inputs.TYPST_GATHER_VER}}"
          crate-name: "typst-gather"
          crate-version: ${{inputs.TYPST_GATHER_VER}}
