name: typst
on:
  workflow_dispatch:
    inputs:
      TYPST_VER:
        description: 'Typst version'
        type: string
        required: true
jobs:
  builds:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install pycargoebuild
        run: |
          pip install pycargoebuild
          wget https://github.com/gentoo/gentoo/raw/refs/heads/master/metadata/license-mapping.conf
          echo "DIST_DIR=${GITHUB_WORKSPACE}/pycargo" >> $GITHUB_ENV
      - name: Download/Extract typst
        run: |
          wget https://github.com/typst/typst/archive/refs/tags/v${{inputs.TYPST_VER}}.tar.gz
          tar xaf v${{inputs.TYPST_VER}}.tar.gz
      #Checkout git sources
      - name: Checkout Current
        uses: actions/checkout@v5
        with:
          path: file_repo
      - name: Pycargobuild
        uses: ./file_repo/.github/actions/pycargoebuild
        with:
          cargo-root-path: "typst-${{inputs.TYPST_VER}}/crates/typst-cli"


